### ISSUE TITLE
Invalid Common structure when creating DID

### ISSUE THREAD

**Issue by bootstrapsp** [bootstrapsp/miu#10]
**Describe the bug**
While attempting to create DID from gRPC client, Miu throws Invalid Common Structure.

@sagar-88  here's the full detailed structure

**To Reproduce**
1. Start miu server 
`python grpc_serverserver.py`
2. Have a grpc client ready with following input for the `CreateAndStoreDID` , 
Following snippet is from a Go client

> a, createDIDErr := d.CreateAndStoreMyDid(ctx, &pb.CreateAndStoreMyDidRequest{
		WalletHandle: 2, // should be dynamic
		DidJson:      &pb.CreateAndStoreMyDidJsonMessage{
			Did: "Ardhnaarishwar",
			Seed:       "Demo",
			CryptoType: "ed25519",
			Cid:        false,
		},
	}

3. Start the client to connect to 5001 port on which server is running

> DEBUG:indy.did:create_and_store_my_did: >>> wallet_handle: 2, did_json: '{"seed": "Demo", "did": "Ardhnaarishwar", "crypto_type": "ed25519", "cid": null}'
DEBUG:indy.did:create_wallet: Creating callback
DEBUG:indy.libindy:create_cb: >>> cb_type: <class 'ctypes.CFUNCTYPE.<locals>.CFunctionType'>
DEBUG:indy.libindy:create_cb: <<< res: <CFunctionType object at 0x7f089858c818>
DEBUG:indy.libindy:do_call: >>> name: indy_create_and_store_my_did, args: (c_int(2), c_char_p(139674892393840), <CFunctionType object at 0x7f089858c818>)
DEBUG:indy.libindy:do_call: Function indy_create_and_store_my_did returned err: 0
DEBUG:indy.libindy:do_call: <<< <Future pending>
INFO:indy.libindy.native.indy.commands:	src/commands/mod.rs:137 | DidCommand command received
INFO:indy.libindy.native.indy.commands.did:	src/commands/did.rs:124 | CreateAndStoreMyDid command received
DEBUG:indy.libindy.native.indy.commands.did:	src/commands/did.rs:189 | create_and_store_my_did >>> wallet_handle: 2, my_did_info_json: MyDidInfo { did: Some("Ardhnaarishwar"), seed: Some("Demo"), crypto_type: Some("ed25519"), cid: None }
DEBUG:indy.libindy:_indy_callback: >>> command_handle: 3, err 113, args: (b'', b'')
DEBUG:indy.libindy:_indy_callback: <<<
DEBUG:indy.libindy:_indy_loop_callback: >>> command_handle: 3, err 113, args: (b'', b'')
WARNING:indy.libindy:_indy_loop_callback: Function returned error 113
DEBUG:indy.libindy:_indy_loop_callback <<<
ERROR:did_service:Exception occurred @ CreateAndStoreMyDid----
ERROR:did_service:ErrorCode.CommonInvalidStructure

**Expected behavior**
Should create a DID

**Screenshots**
-NA-

**Desktop (please complete the following information):**
 - OS: ubuntu 16

**Smartphone (please complete the following information):**
-NA-

**Additional context**
-NA-

**Comment by vlmold** [comment]
as you can see from these screens, ERROR:did_service:ErrorCode.CommonInvalidStructure didn't give enough information before. but the real reason was in parameter format. 

When I call this function with these params : 
DID format :
![image](https://user-images.githubusercontent.com/20798481/76792715-4a8d8780-67cc-11ea-98f4-8e0127f5e666.png)
Seed format: 
![image](https://user-images.githubusercontent.com/20798481/76792764-698c1980-67cc-11ea-8492-767a0493268d.png)

For example, for these params everything works good. 
Did : Y87wM6ceVarBmzcPTqPGdw
Seed: b2fff055f8d649d0e91ac71e889ba849372612d3ff2968109245cad79770b3d1

client code example :
```
seed,err := base58.Decode("D3jvacNU1TCUFXkM8mJAr5zcPpXdvMgzFqUVeTP4BJqE")
	hexSeed := hex.EncodeToString(seed)


	pub, _, err := ed25519.GenerateKey(bytes.NewReader(seed))

	encodedDID := base58.Encode(pub[:16])

	fmt.Println(encodedDID) //len(encodedDID) = 22, encoded 16 byte value

	fmt.Println(hexSeed)

	csResponse, err := didServiceClient.CreateAndStoreMyDid(context.Background(),
		&identitylayer.CreateAndStoreMyDidRequest{WalletHandle: walletResponse.WalletHandle,
			DidJson: &identitylayer.CreateAndStoreMyDidJsonMessage{
				Did: encodedDID,
				Seed: hexSeed,
				CryptoType: "ed25519",
				Cid: false,
	}})
```

**Comment by bootstrapsp** [comment]
thanks for highlighting the short-comings - whole error handling layer needs major overhaul! I am gonna start looking into that as time permits. Much appreciated!
