### ISSUE TITLE
Multiple 'No positional arguments allowed'.No  Handling for specific IndyError

### ISSUE THREAD

**Issue by vlmold** [bootstrapsp/miu#16]
**Describe the bug**
After performing calls to Indy library and trying to send result back to gRPC client,  Miu throws errors, because of not specifying arguments name for protobuf. Also there is no possibility to determine if error is IndyError and send more appropriate  error message.
see below
**To Reproduce**
1. run grpc server Miu 
2.use this code

```
	conn, err := grpc.Dial("localhost:50051", grpc.WithInsecure())
	if err != nil {
		panic(err)
	}

	//create  poolServiceClient service

	poolServiceClient := identitylayer.NewPoolServiceClient(conn)
	pcr, err := poolServiceClient.CreatePoolLedgerConfig(context.Background(), &identitylayer.CreatePoolLedgerConfigRequest{ConfigName: poolName, Config: &identitylayer.ConfigCreatePoolLedger{GensisTxn: "/path_to_genesis"}})

	if err != nil {
		panic(err)
	}
	fmt.Printf("Pool creation result %d \n", pcr.GetErrorCode())
```
3. Run gRPC client to connect to Miu 
4. Get 'positional argument error'

**Expected behavior**
1) get 0 as error Code if pool created successfully.
2) get 306 error Code if pool has already been created
3) get Internal error Code in case  other error happenned

**Screenshots**
![image](https://user-images.githubusercontent.com/20798481/76707743-8b1cd080-66fa-11ea-84a2-37ce582198a4.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6

**Additional context**
It's quite common issue in plenty of methods. So PR for IndyError handler and fixing 'no positional arguments allowed' is extremely needed

**Comment by vlmold** [comment]
created a PR for this. 
https://github.com/bootstrapsp/miu/pull/17

**Comment by bootstrapsp** [comment]
as suggested PR's merged.
