### ISSUE TITLE
Return Wallet / Pool Handler of already opened wallet / pool together with Message 'AlreadyOpened'

### ISSUE THREAD

**Issue by vlmold** [bootstrapsp/miu#18]
**Is your feature request related to a problem? Please describe.**
When you're attempting to open wallet / pool that has already been opened it's not possible to receive opened entity handle, so it's not possible to use it, even if you have rights.
indy-cli allows to use wallet if it was opened before.

**Describe the solution you'd like**
We could add simple layer of memory storage for opened Pools and opened Wallets. If wallet / pool is opened - return wallet handle from memory with message that wallet was opened before, of course if user has right credentials to wallet.

example 
![image](https://user-images.githubusercontent.com/20798481/76740300-58b0b900-6776-11ea-8f5a-14cd746c508f.png)

where openPools is memory dictionary. 

**Describe alternatives you've considered**
List of pools could return configs and handles if they're opened.

**Additional context**
This feature will help to use the same wallet from several client service instances without storing handle on service side.

**Comment by vlmold** [comment]
I'm ready to implement this.

**Comment by bootstrapsp** [comment]
@vladyslavmunin  will this need rpc definition change too? Thanks for helping out on this!

**Comment by vlmold** [comment]
https://github.com/bootstrapsp/miu/pull/20

**Comment by vlmold** [comment]
> will this need rpc definition change too? Thanks for helping out on this!

gRPC response messages OpenPoolLedgerResponse and OpenWalletHandle are changed. ErrorCode field is added.

**Comment by bootstrapsp** [comment]
thanks, yes I saw you updated the proto already. I guess this issue can then be closed?

**Comment by vlmold** [comment]
yes
